# Generated by Django 3.2.15 on 2022-09-25 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название группы.', max_length=200, verbose_name='Имя контакта.')),
                ('is_family', models.BooleanField(help_text='Член семьи.', verbose_name='Член семьи.')),
                ('email', models.EmailField(default='email@email.ru', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Phone', 'Phone'), ('Meeting', 'Meeting'), ('Chat', 'Chat'), ('Video', 'Video')], max_length=10)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата коммуникации.')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication', to='contacts.contact', verbose_name='Контакт')),
            ],
        ),
    ]
