# Generated by Django 3.2.15 on 2022-11-19 12:05

import contacts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.CharField(help_text='Для Юр.лица - 10 цифр,для Физ.лица - 12.', max_length=12, validators=[contacts.validators.validate_inn], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='kpp',
            field=models.CharField(blank=True, help_text='Код Причины Постановки. КПП состоит из 9 цифр.', max_length=9, null=True, validators=[contacts.validators.validate_kpp], verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='company',
            name='okpo',
            field=models.CharField(blank=True, help_text='Укажите ОКПО. Для Юр.лица - 8 цифр, для Физ.лица(ИП) - 10 цифр.,', max_length=10, null=True, validators=[contacts.validators.validate_okpo], verbose_name='ОКПО'),
        ),
    ]
