# Generated by Django 3.2.15 on 2022-09-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='frequency_of_communications_days',
            field=models.IntegerField(blank=True, default=12),
            preserve_default=False,
        ),
    ]
