# Generated by Django 3.2.15 on 2022-09-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_communication_date_of_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='date_of_birthday',
        ),
        migrations.AddField(
            model_name='contact',
            name='date_of_birthday',
            field=models.DateTimeField(blank=True, default='2011-09-29', verbose_name='Дата рождения.'),
        ),
    ]
