# Generated by Django 3.2.15 on 2022-12-21 10:25

import contacts.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='contact',
            field=models.ForeignKey(help_text='Укажите контакт', on_delete=django.db.models.deletion.CASCADE, related_name='communication', to='contacts.contact', verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='done_date',
            field=models.DateTimeField(blank=True, help_text='Укажите дату', null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='info',
            field=models.TextField(blank=True, default='Добавьие описание', help_text='Добавьте описание', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='plan_date',
            field=models.DateTimeField(blank=True, help_text='Укажите планируемую дату', null=True, verbose_name='Планируемая дата'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Укажите дату создания', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='status',
            field=models.CharField(blank=True, choices=[('Выполнено', 'Выполнено'), ('Запланировано', 'Запланировано')], help_text='Укажите статус', max_length=20, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='type',
            field=models.CharField(choices=[('Звонок', 'Звонок'), ('Встреча', 'Встреча'), ('Переписка', 'Переписка'), ('Видео-звонок', 'Видео-звонок')], help_text='Укажите тип', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.CharField(help_text='Укажите ИНН. Для Юр.лица - 10 цифр,для Физ.лица - 12', max_length=12, validators=[contacts.validators.validate_inn], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='kpp',
            field=models.CharField(blank=True, help_text='Укажите КПП. Состоит из 9 цифр', max_length=9, null=True, validators=[contacts.validators.validate_kpp], verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mobile_number_of_head',
            field=models.CharField(blank=True, help_text='Укажите номер телефона.', max_length=30, null=True, validators=[contacts.validators.validate_mobile_phone_number], verbose_name='Мобильный телефон директора'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ogrn',
            field=models.CharField(blank=True, help_text='Укажите ОГРН. Состоит из 13 цифр', max_length=13, null=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='okpo',
            field=models.CharField(blank=True, help_text='Укажите ОКПО. Для Юр.лица - 8 цифр, для Физ.лица(ИП) - 10 цифр', max_length=10, null=True, validators=[contacts.validators.validate_okpo], verbose_name='ОКПО'),
        ),
    ]
