# Generated by Django 3.2.15 on 2022-10-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20220926_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='info',
            field=models.TextField(default='Без описания', help_text='Добавьте описние', verbose_name='Описание коммуникации'),
            preserve_default=False,
        ),
    ]
