# Generated by Django 3.2.15 on 2022-12-26 17:28

import contacts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20221221_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='full_name',
            field=models.CharField(blank=True, help_text='Укажите полное наименование.', max_length=200, null=True, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.CharField(blank=True, help_text='Укажите ИНН. Для Юр.лица - 10 цифр,для Физ.лица - 12', max_length=12, null=True, validators=[contacts.validators.validate_inn], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_adress',
            field=models.TextField(blank=True, help_text='Укажите юридический адрес.', null=True, verbose_name='Юридический адрес'),
        ),
    ]
