# Generated by Django 3.2.15 on 2023-01-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20221226_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Тип бутылок')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='bottles',
            field=models.ManyToManyField(blank=True, null=True, to='contacts.Bottle', verbose_name='бутылки'),
        ),
    ]
