# Generated by Django 3.2.15 on 2023-02-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20230105_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='bottles',
        ),
        migrations.AddField(
            model_name='company',
            name='test_field',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='status',
            field=models.CharField(blank=True, choices=[('done', 'Выполнено'), ('plan', 'Запланировано')], help_text='Укажите статус', max_length=20, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='type',
            field=models.CharField(choices=[('call', 'Звонок'), ('meeting', 'Встреча'), ('chat', 'Переписка'), ('video', 'Видео-звонок')], help_text='Укажите тип', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(blank=True, choices=[('family', 'Член семьи'), ('slave', 'Подчиненый'), ('comrade', 'Товарищ'), ('collegue', 'Коллега'), ('master', 'Руководитель'), ('partner', 'Деловой партнер')], help_text='Выберите роль контакта.', max_length=20, null=True, verbose_name='Роль контакта'),
        ),
        migrations.DeleteModel(
            name='Bottle',
        ),
    ]
