# Generated by Django 3.2.15 on 2022-10-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_communication_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='type',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Meeting', 'Meeting'), ('Chat', 'Chat'), ('Video', 'Video')], max_length=10),
        ),
    ]
