# Generated by Django 3.2.15 on 2022-10-01 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20221001_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='contacts.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='company',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='company',
            name='okpo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ОКПО'),
        ),
        migrations.AlterField(
            model_name='company',
            name='short_name',
            field=models.CharField(max_length=150, verbose_name='Сокращенное наименование'),
        ),
    ]
