# Generated by Django 3.2.15 on 2022-10-03 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20221001_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='contacts.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_of_birthday',
            field=models.DateTimeField(blank=True, default='2011-09-29', null=True, verbose_name='Дата рождения.'),
        ),
    ]
