# Generated by Django 3.2.15 on 2022-10-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20221003_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bic',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cor_acount',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Корреспондентский счет'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fact_adress',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='head_of_company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО руководителя'),
        ),
        migrations.AlterField(
            model_name='company',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='company',
            name='main_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Основной email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='number_acount',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Расчетный счет'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ogrn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='okved',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ОКВЭД'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='company',
            name='short_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Сокращенное наименование'),
        ),
    ]
