# Generated by Django 3.2.15 on 2023-03-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_alter_company_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='test_field',
        ),
        migrations.AddField(
            model_name='company',
            name='choice_int',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1),
            preserve_default=False,
        ),
    ]
