# Generated by Django 3.2.15 on 2022-10-03 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20221003_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_family',
        ),
        migrations.AddField(
            model_name='contact',
            name='role',
            field=models.CharField(blank=True, choices=[('Член семьи', 'Член семьи'), ('Подчиненый', 'Подчиненый'), ('Товарищ', 'Товарищ'), ('Коллега', 'Коллега'), ('Деловой партнер', 'Деловой партнер')], help_text='Это член семьи?', max_length=20, null=True, verbose_name='Член семьи'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Укажите компанию контакта.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='contacts.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_of_birthday',
            field=models.DateTimeField(blank=True, help_text='Укажите день рождения контакта.', null=True, verbose_name='Дата рождения.'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, help_text='Укажите основной email.', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='frequency_of_communications_days',
            field=models.IntegerField(help_text='Укажите как часто хотите общаться с контактом.', verbose_name='Частота коммуникаций. Раз/дней.'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='Укажите фамилию и имя контакта.', max_length=200, verbose_name='Имя контакта'),
        ),
    ]
