# Generated by Django 3.2.15 on 2022-10-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_auto_20221003_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='position',
            field=models.CharField(default=1, help_text='Укажите должность контакта.', max_length=200, verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
