# Generated by Django 3.2.15 on 2022-10-05 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_contact_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='status',
            field=models.CharField(choices=[('Выполнена', 'Выполнена'), ('Запланирована', 'Запланирована'), ('Просрочена', 'Просрочена')], default='Выполнена', help_text='Укажите статус коммуникации.', max_length=20, verbose_name='Статус.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communication',
            name='contact',
            field=models.ForeignKey(help_text='Укажите контакт коммуникаиции.', on_delete=django.db.models.deletion.CASCADE, related_name='communication', to='contacts.contact', verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата контакта.', verbose_name='Дата коммуникации.'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='type',
            field=models.CharField(choices=[('Звонок', 'Звонок'), ('Встреча', 'Встреча'), ('Переписка', 'Переписка'), ('Видео-звонок', 'Видео-звонок')], help_text='Укажите тип комуникации.', max_length=20, verbose_name='Тип коммуникации.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bic',
            field=models.CharField(blank=True, help_text='Укажите БИК банка.', max_length=9, null=True, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cor_acount',
            field=models.CharField(blank=True, help_text='Укажите номер кореспондентского счета.', max_length=20, null=True, verbose_name='Корреспондентский счет'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fact_adress',
            field=models.TextField(blank=True, help_text='Укажите фактический адрес.', max_length=10, null=True, verbose_name='Фактический адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='full_name',
            field=models.CharField(help_text='Укажите полное наименование.', max_length=200, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='company',
            name='head_of_company',
            field=models.CharField(blank=True, help_text='Укажите ФИО руководителя компании.', max_length=200, null=True, verbose_name='ФИО руководителя'),
        ),
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.CharField(help_text='Укажите ИНН.', max_length=10, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='kpp',
            field=models.CharField(blank=True, help_text='Укажите КПП.', max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_adress',
            field=models.TextField(help_text='Укажите юридический адрес.', verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='main_email',
            field=models.EmailField(blank=True, help_text='Укажите основной email.', max_length=254, null=True, verbose_name='Основной email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='number_acount',
            field=models.CharField(blank=True, help_text='Укажите номер расчетного счета.', max_length=20, null=True, verbose_name='Расчетный счет'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ogrn',
            field=models.CharField(blank=True, help_text='Укажите ОГРН.', max_length=13, null=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='okpo',
            field=models.CharField(blank=True, help_text='Укажите ОКПО.', max_length=10, null=True, verbose_name='ОКПО'),
        ),
        migrations.AlterField(
            model_name='company',
            name='okved',
            field=models.CharField(blank=True, help_text='Укажите ОКВЭД.', max_length=10, null=True, verbose_name='ОКВЭД'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Укажите номер телефона.', max_length=30, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='company',
            name='short_name',
            field=models.CharField(help_text='Укажите сокращенное наименование.', max_length=150, verbose_name='Сокращенное наименование'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(blank=True, choices=[('Член семьи', 'Член семьи'), ('Подчиненый', 'Подчиненый'), ('Товарищ', 'Товарищ'), ('Коллега', 'Коллега'), ('Деловой партнер', 'Деловой партнер')], help_text='Выберите роль контакта.', max_length=20, null=True, verbose_name='Роль контакта'),
        ),
    ]
