# Generated by Django 3.2.15 on 2022-10-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_auto_20221006_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='status',
            field=models.CharField(blank=True, choices=[('Выполнена', 'Выполнена'), ('Запланирована', 'Запланирована'), ('Просрочена', 'Просрочена')], help_text='Укажите статус коммуникации.', max_length=20, null=True, verbose_name='Статус.'),
        ),
    ]
