# Generated by Django 3.2.15 on 2022-10-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_alter_communication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='plan_date',
            field=models.DateTimeField(blank=True, help_text='Планируемая дата взаимодействия.', null=True, verbose_name='Планирование дата коммуникации.'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='status',
            field=models.CharField(blank=True, choices=[('Выполнена', 'Выполнена'), ('Запланировано', 'Запланировано')], help_text='Укажите статус коммуникации.', max_length=20, null=True, verbose_name='Статус.'),
        ),
    ]
