# Generated by Django 3.2.15 on 2022-10-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0018_auto_20221006_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='status',
            field=models.CharField(blank=True, choices=[('Выполнено', 'Выполнено'), ('Запланировано', 'Запланировано')], help_text='Укажите статус коммуникации.', max_length=20, null=True, verbose_name='Статус.'),
        ),
    ]
