# Generated by Django 3.2.15 on 2022-10-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_alter_communication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='done_date',
            field=models.DateTimeField(blank=True, help_text='Планируемая дата взаимодействия.', null=True, verbose_name='Дата коммуникации.'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='plan_date',
            field=models.DateTimeField(blank=True, help_text='Планируемая дата коммуникации.', null=True, verbose_name='Планируемая дата коммуникации.'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата создания коммуникации.', verbose_name='Дата создания объекта коммуникации.'),
        ),
    ]
