# Generated by Django 3.2.15 on 2022-10-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_auto_20221007_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='fact_adress',
            field=models.TextField(blank=True, help_text='Укажите фактический адрес.', null=True, verbose_name='Фактический адрес'),
        ),
    ]
