# Generated by Django 3.2.15 on 2022-10-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_alter_company_fact_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Укажите номер телефона.', max_length=30, null=True, verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Укажите номер телефона.', max_length=30, null=True, verbose_name='Мобильный телефон'),
        ),
    ]
