# Generated by Django 3.2.15 on 2022-10-26 07:32

import contacts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0022_auto_20221026_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Укажите номер телефона.', max_length=30, null=True, validators=[contacts.validators.validate_phone_number], verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Укажите номер телефона.', max_length=30, null=True, validators=[contacts.validators.validate_phone_number], verbose_name='Мобильный телефон'),
        ),
    ]
