# Generated by Django 3.2.15 on 2022-10-26 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название проекта.', max_length=200, verbose_name='Название проекта.')),
                ('revenue', models.IntegerField(help_text='Укажите выручку.', verbose_name='Выручка от проекта.')),
                ('deadline', models.DateField(help_text='Дедлайн.', verbose_name='Дедлайн.')),
                ('my_role', models.CharField(help_text='Роль в проекте.', max_length=200, verbose_name='Роль в проекте.')),
                ('status', models.CharField(choices=[('В работе', 'В работе'), ('Завершен', 'Завершен')], help_text='Статус проекта.', max_length=200, verbose_name='Статус проекта')),
                ('customer', models.ForeignKey(help_text='Укажите заказчика.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='contacts.company', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ('deadline',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Что нужно сделать.', max_length=200, verbose_name='Тескт задачи')),
                ('deadline', models.DateTimeField(help_text='Дедлайн задачи.', verbose_name='Дедлайн задачи.')),
                ('project', models.ForeignKey(blank=True, help_text='Укажите к какому проекту относится задача.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ('deadline',),
            },
        ),
        migrations.CreateModel(
            name='ProjectContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Роль в проекте.', max_length=200, verbose_name='Роль в проекте.')),
                ('contact', models.ForeignKey(help_text='Укажите контакт проекта.', on_delete=django.db.models.deletion.CASCADE, related_name='contact_project', to='contacts.contact', verbose_name='Контакт')),
                ('project', models.ForeignKey(help_text='Укажите проект контакта.', on_delete=django.db.models.deletion.CASCADE, related_name='contact_project', to='tasks.project', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название проекта.', max_length=200, verbose_name='Название проекта.')),
                ('revenue', models.IntegerField(help_text='Укажите выручку.', verbose_name='Выручка от проекта.')),
                ('status', models.CharField(choices=[('Получена заявка', 'Получена заявка'), ('На стороне клиента', 'На стороне клиента'), ('На моей стороне', 'На моей стороне'), ('Завершен сделкой', 'Завершен сделкой'), ('Потерян', 'Потерян')], help_text='Статус интереса.', max_length=200, verbose_name='Статус интереса')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дедлайн задачи.', verbose_name='Дата создания.')),
                ('main_contact', models.ForeignKey(help_text='Укажите контакт который работает в этой компании.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interests', to='contacts.contact', verbose_name='Основной контакт')),
                ('partner', models.ForeignKey(help_text='Укажите заказчика.', on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='contacts.company', verbose_name='Заказчик')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication', models.ForeignKey(help_text='Укажите коммуникацию.', on_delete=django.db.models.deletion.CASCADE, related_name='project', to='contacts.communication', verbose_name='Коммуникация.')),
                ('project', models.ForeignKey(help_text='Укажите проект.', on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='tasks.project', verbose_name='Интерес.')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication', models.ForeignKey(help_text='Укажите коммуникацию.', on_delete=django.db.models.deletion.CASCADE, related_name='interest', to='contacts.communication', verbose_name='Коммуникация.')),
                ('interest', models.ForeignKey(help_text='Укажите интерес.', on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='tasks.interest', verbose_name='Интерес.')),
            ],
        ),
    ]
