# Generated by Django 3.2.15 on 2022-10-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Что нужно сделать.', max_length=200, verbose_name='Тескт задачи')),
                ('deadline', models.DateTimeField(help_text='Планируемая дата коммуникации.', verbose_name='Планируемая дата коммуникации.')),
            ],
        ),
    ]
