# Generated by Django 3.2.15 on 2022-11-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='routine',
            field=models.BooleanField(null=True),
        ),
    ]
