# Generated by Django 3.2.15 on 2022-10-11 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_auto_20221007_2341'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название проекта.', max_length=200, verbose_name='Название проекта.')),
                ('revenue', models.IntegerField(help_text='Укажите выручку.', verbose_name='Выручка от проекта.')),
                ('deadline', models.DateTimeField(help_text='Дедлайн.', verbose_name='Дедлайн.')),
                ('my_role', models.CharField(help_text='Роль в проекте.', max_length=200, verbose_name='Роль в проекте.')),
                ('status', models.CharField(choices=[('Запланирован', 'Запланирован'), ('В работе', 'В работе')], help_text='Статус проекта.', max_length=200, verbose_name='Статус проекта')),
                ('customer', models.ForeignKey(help_text='Укажите заказчика.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='contacts.company', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ('deadline',),
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('deadline',), 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(help_text='Дедлайн задачи.', verbose_name='Дедлайн задачи.'),
        ),
        migrations.CreateModel(
            name='ProjectContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Роль в проекте.', max_length=200, verbose_name='Роль в проекте.')),
                ('contact', models.ForeignKey(help_text='Укажите контакт проекта.', on_delete=django.db.models.deletion.CASCADE, related_name='contact_project', to='contacts.contact', verbose_name='Контакт')),
                ('project', models.ForeignKey(help_text='Укажите проект контакта.', on_delete=django.db.models.deletion.CASCADE, related_name='contact_project', to='tasks.project', verbose_name='Проект')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(help_text='Укажите к какому проекту относится задача.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.project', verbose_name='Проект'),
        ),
    ]
