# Generated by Django 3.2.15 on 2022-10-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20221011_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(help_text='Дедлайн.', verbose_name='Дедлайн.'),
        ),
    ]
