# Generated by Django 3.2.15 on 2022-11-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='regularity',
            field=models.SmallIntegerField(default=1, verbose_name='Регулярность задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='routine',
            field=models.BooleanField(default=1, verbose_name='Регулярная задача?'),
            preserve_default=False,
        ),
    ]
