# Generated by Django 3.2.15 on 2022-11-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20221124_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='Добавьте описание задачи', null=True, verbose_name='Описание задачи'),
        ),
    ]
