# Generated by Django 3.2.15 on 2022-10-13 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_auto_20221007_2341'),
        ('tasks', '0003_alter_project_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('В работе', 'В работе'), ('Завершен', 'Завершен')], help_text='Статус проекта.', max_length=200, verbose_name='Статус проекта'),
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название проекта.', max_length=200, verbose_name='Название проекта.')),
                ('revenue', models.IntegerField(help_text='Укажите выручку.', verbose_name='Выручка от проекта.')),
                ('status', models.CharField(choices=[('Получена заявка', 'Получена заявка'), ('На стороне клиента', 'На стороне клиента'), ('На моей стороне', 'На моей стороне')], help_text='Статус интереса.', max_length=200, verbose_name='Статус интереса')),
                ('partner', models.ForeignKey(help_text='Укажите заказчика.', on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='contacts.company', verbose_name='Заказчик')),
            ],
        ),
    ]
