# Generated by Django 3.2.15 on 2022-10-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20221013_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default='2022-01-01 00:00', help_text='Дедлайн задачи.', verbose_name='Дата создания.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='status',
            field=models.CharField(choices=[('Получена заявка', 'Получена заявка'), ('На стороне клиента', 'На стороне клиента'), ('На моей стороне', 'На моей стороне'), ('Завершен сделкой', 'Завершен сделкой'), ('Потерян', 'Потерян')], help_text='Статус интереса.', max_length=200, verbose_name='Статус интереса'),
        ),
    ]
