# Generated by Django 3.2.15 on 2022-11-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(null=True, verbose_name='Выполнена?'),
        ),
    ]
