# Generated by Django 3.2.15 on 2022-11-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=True, verbose_name='Выполнена?'),
            preserve_default=False,
        ),
    ]
