# Generated by Django 3.2.15 on 2022-11-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='next_task',
            field=models.IntegerField(null=True, verbose_name='pk следующей задачи.'),
        ),
    ]
