# Generated by Django 3.2.15 on 2022-10-17 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_alter_company_fact_adress'),
        ('tasks', '0008_communicationsinterest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommunicationsInterest',
            new_name='CommunicationInterest',
        ),
        migrations.CreateModel(
            name='CommunicationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication', models.ForeignKey(help_text='Укажите коммуникацию.', on_delete=django.db.models.deletion.CASCADE, related_name='project', to='contacts.communication', verbose_name='Коммуникация.')),
                ('project', models.ForeignKey(help_text='Укажите интерес.', on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='tasks.project', verbose_name='Интерес.')),
            ],
        ),
    ]
