# Generated by Django 3.2.15 on 2022-11-27 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20221126_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='interest',
            field=models.ForeignKey(blank=True, help_text='Укажите к какому интересу относится задача.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.interest', verbose_name='Интерес'),
        ),
    ]
