# Generated by Django 3.2.15 on 2022-10-25 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20221017_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationproject',
            name='project',
            field=models.ForeignKey(help_text='Укажите проект.', on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='tasks.project', verbose_name='Интерес.'),
        ),
    ]
