# Generated by Django 3.2.15 on 2022-11-27 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_edit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего сохранения.'),
        ),
        migrations.AddField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default='2000-01-01 00:00', verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Укажите категорию задачи.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.categorytask', verbose_name='Категория задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(help_text='Дедлайн задачи.', verbose_name='Дедлайн задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Добавьте описание задачи', null=True, verbose_name='Описание задачи'),
        ),
    ]
