# Generated by Django 3.2.15 on 2022-11-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20221128_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
