# Generated by Django 3.2.15 on 2022-12-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Не выполнен', 'Не выполнен'), ('В работе', 'В работе'), ('Завершен', 'Завершен')], default='Не выполнен', max_length=20, verbose_name='Статус задачи'),
            preserve_default=False,
        ),
    ]
