# Generated by Django 3.2.15 on 2023-04-07 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20230407_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Приоритет задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(help_text='Когда дедлайн?', verbose_name='Дедлайн задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Добавьте описание', null=True, verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(help_text='Что нужно сделать?', max_length=200, verbose_name='Тескт задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Задача проекта.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='task',
            name='regularity',
            field=models.SmallIntegerField(default=1, verbose_name='Регулярность'),
        ),
        migrations.AlterField(
            model_name='task',
            name='routine',
            field=models.BooleanField(verbose_name='Повторяющаяся задача?'),
        ),
        migrations.DeleteModel(
            name='CategoryTask',
        ),
    ]
