# Generated by Django 3.2.15 on 2023-04-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_auto_20230407_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='done_date',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Создан', 'Создан'), ('Требуется разбить на подзадачи', 'Требуется разбить на подзадачи'), ('В работе', 'В работе'), ('Завершен', 'Завершен')], max_length=40, verbose_name='Статус задачи'),
        ),
    ]
