# Generated by Django 3.2.15 on 2023-04-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_auto_20230410_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='new',
            field=models.BooleanField(default=1, verbose_name='Новые'),
            preserve_default=False,
        ),
    ]
