# Generated by Django 3.2.15 on 2023-04-12 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_task_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='top_task',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='down_tasks', to='tasks.task', verbose_name='Родительская задача'),
        ),
    ]
