# Generated by Django 3.2.15 on 2023-04-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_task_top_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='done',
        ),
        migrations.RemoveField(
            model_name='task',
            name='new',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('В работе', 'В работе'), ('Завершена', 'Завершена'), ('Отменена', 'Отменена')], max_length=40, verbose_name='Статус задачи'),
        ),
    ]
