# Generated by Django 3.2.15 on 2022-11-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20221122_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(help_text='Добавьте описание сборки', null=True, verbose_name='Описание сборки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('шт', 'шт'), ('м', 'м'), ('кг', 'кг')], max_length=10, verbose_name='Еденица измерения'),
        ),
    ]
