# Generated by Django 3.2.15 on 2022-11-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20221123_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('м', 'м'), ('шт', 'шт'), ('кг', 'кг')], max_length=10, verbose_name='Еденица измерения'),
        ),
    ]
