# Generated by Django 3.2.15 on 2022-12-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='plant_position',
            field=models.BooleanField(default=False, help_text='Укажите, позиция является складской?', verbose_name='Складская позиция'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('шт', 'шт'), ('кг', 'кг'), ('м', 'м')], max_length=10, verbose_name='Еденица измерения'),
        ),
    ]
