# Generated by Django 3.2.15 on 2022-12-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20221221_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_plants_position',
            field=models.PositiveIntegerField(blank=True, help_text='Укажите, сколько положить на склад', null=True, verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('м', 'м'), ('кг', 'кг'), ('шт', 'шт')], max_length=10, verbose_name='Еденица измерения'),
        ),
    ]
