# Generated by Django 3.2.15 on 2022-12-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20221221_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('кг', 'кг'), ('м', 'м'), ('шт', 'шт')], max_length=10, verbose_name='Еденица измерения'),
        ),
    ]
