# Generated by Django 3.2.15 on 2023-02-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('шт', 'шт'), ('м', 'м'), ('кг', 'кг')], max_length=10, verbose_name='Еденица измерения'),
        ),
    ]
